# Generated by Django 4.2.7 on 2024-06-24 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRaw',
            fields=[
                ('record_timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'energy_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GasConsumption',
            fields=[
                ('record_timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('previous_timestamp', models.DateTimeField()),
                ('time_interval', models.CharField(max_length=255)),
                ('time_seconds', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('total_consumption', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('consumption_m3_per_h', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'er_gas_consumption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolarForecast',
            fields=[
                ('record_timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'solar_forecast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('declination', models.IntegerField()),
                ('azimuth', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solar_plant',
            },
        ),
    ]
